package: "."
env:
  OPENSSL_CONF: /etc/ssl/openssl.cnf
capabilities:
  database:
    engine: mysql
volumes:
  - name: wp-content
    mount: /app/wp-content
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
enable_email: true
